var myString;
var myNumber;
var myBoolean;
var myAny;
// let strArray:string[];
// let numArray:number[];
// let boolArray:boolean[];
// let anyArray:any[];
//or
var strArray;
var numArray;
var boolArray;
var anyArray;
var myVoid = undefined;
var myNull = null;
var myUndefined = undefined;
myString = "Hello TypeScript Dev";
myNumber = 9;
myBoolean = true;
myAny = '1' + 2;
strArray = ['Type', 'Script'];
numArray = [10, 20];
boolArray = [true, false];
anyArray = ['number', 9, true];
console.log(myString);
console.log(myNumber);
console.log(myBoolean);
console.log(myAny);
console.log(strArray);
console.log(numArray);
console.log(boolArray);
console.log(anyArray);
